[package]
name = "rusted_instrument_designer"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.4.1"

[dev-dependencies]
insta = { version = "1.17.1", features = ["backtrace", "redactions"] }
pretty_assertions = "1"
clap = "4.1.8"
